### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by lishine** [malerba118/react-delta#5]
Hi
Typescript complains about this
```ts
  useConditionalEffect(() => {
    console.log("Window got narrower");
  }, delta && delta.prev && delta.curr < delta.prev);
```
It works only like this:
```ts
  useConditionalEffect(() => {
    console.log("Window got narrower");
  }, !!delta && !!delta.prev && delta.curr < delta.prev);
```

**Comment by malerba118** [comment]
Hi, yes. Right now it's expecting a boolean for the second argument. I can update it to accept `any` and i'll just coerce the value to a boolean internally. I'll try to have this published with a few other updates in a week or so.

**Comment by malerba118** [comment]
@lishine  this is resolved now in  [v1.1.0](https://www.npmjs.com/package/react-delta#useconditionaleffectcallback-condition)! That parameter now accepts type any.

**Comment by lishine** [comment]
Great!
BTW I don't know if it is the best DSL :) I mean, maybe better to be explicit: !! :)

**Comment by malerba118** [comment]
From i theoretical standpoint i think i slightly prefer it typed as a boolean, but from a practical standpoint it seems like a nice convenience to allow people to pass in anything
