### ISSUE TITLE
Question: How does useConditionalEffect handle dependencies?

### ISSUE THREAD

**Issue by Sheldonfrith** [malerba118/react-delta#7]
I'm assuming I don't need to worry about dependencies when using 'useConditionalEffect' like I would have to if using 'useEffect'?

Thanks for making these hooks by the way!

**Comment by malerba118** [comment]
That’s correct! No need to specify dependencies anywhere, just the boolean. And sure thing, hope they’re useful!

**Comment by Sheldonfrith** [comment]
Thanks!
